// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwipeWords.Data;

#nullable disable

namespace SwipeWord.Migrations.FlashcardGameDatabase
{
    [DbContext(typeof(FlashcardGameDatabaseContext))]
    partial class FlashcardGameDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SwipeWords.Data.CorrectWord", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordId");

                    b.ToTable("CorrectWords");

                    b.HasData(
                        new
                        {
                            WordId = 1,
                            Frequency = 100,
                            Word = "apple"
                        },
                        new
                        {
                            WordId = 2,
                            Frequency = 200,
                            Word = "banana"
                        },
                        new
                        {
                            WordId = 3,
                            Frequency = 150,
                            Word = "cherry"
                        },
                        new
                        {
                            WordId = 4,
                            Frequency = 120,
                            Word = "date"
                        },
                        new
                        {
                            WordId = 5,
                            Frequency = 110,
                            Word = "elderberry"
                        },
                        new
                        {
                            WordId = 6,
                            Frequency = 130,
                            Word = "fig"
                        },
                        new
                        {
                            WordId = 7,
                            Frequency = 140,
                            Word = "grape"
                        },
                        new
                        {
                            WordId = 8,
                            Frequency = 160,
                            Word = "honeydew"
                        },
                        new
                        {
                            WordId = 9,
                            Frequency = 170,
                            Word = "kiwi"
                        },
                        new
                        {
                            WordId = 10,
                            Frequency = 180,
                            Word = "lemon"
                        },
                        new
                        {
                            WordId = 11,
                            Frequency = 190,
                            Word = "mango"
                        },
                        new
                        {
                            WordId = 12,
                            Frequency = 210,
                            Word = "nectarine"
                        },
                        new
                        {
                            WordId = 13,
                            Frequency = 220,
                            Word = "orange"
                        },
                        new
                        {
                            WordId = 14,
                            Frequency = 230,
                            Word = "papaya"
                        },
                        new
                        {
                            WordId = 15,
                            Frequency = 240,
                            Word = "quince"
                        },
                        new
                        {
                            WordId = 16,
                            Frequency = 250,
                            Word = "raspberry"
                        },
                        new
                        {
                            WordId = 17,
                            Frequency = 260,
                            Word = "strawberry"
                        },
                        new
                        {
                            WordId = 18,
                            Frequency = 270,
                            Word = "tangerine"
                        },
                        new
                        {
                            WordId = 19,
                            Frequency = 280,
                            Word = "ugli"
                        },
                        new
                        {
                            WordId = 20,
                            Frequency = 290,
                            Word = "vanilla"
                        },
                        new
                        {
                            WordId = 21,
                            Frequency = 300,
                            Word = "watermelon"
                        },
                        new
                        {
                            WordId = 22,
                            Frequency = 310,
                            Word = "xigua"
                        },
                        new
                        {
                            WordId = 23,
                            Frequency = 320,
                            Word = "yellowfruit"
                        },
                        new
                        {
                            WordId = 24,
                            Frequency = 330,
                            Word = "zucchini"
                        },
                        new
                        {
                            WordId = 25,
                            Frequency = 340,
                            Word = "apricot"
                        },
                        new
                        {
                            WordId = 26,
                            Frequency = 350,
                            Word = "blackberry"
                        },
                        new
                        {
                            WordId = 27,
                            Frequency = 360,
                            Word = "cantaloupe"
                        },
                        new
                        {
                            WordId = 28,
                            Frequency = 370,
                            Word = "dragonfruit"
                        },
                        new
                        {
                            WordId = 29,
                            Frequency = 380,
                            Word = "elderflower"
                        },
                        new
                        {
                            WordId = 30,
                            Frequency = 390,
                            Word = "figs"
                        },
                        new
                        {
                            WordId = 31,
                            Frequency = 400,
                            Word = "grapefruit"
                        },
                        new
                        {
                            WordId = 32,
                            Frequency = 410,
                            Word = "huckleberry"
                        },
                        new
                        {
                            WordId = 33,
                            Frequency = 420,
                            Word = "indianfig"
                        },
                        new
                        {
                            WordId = 34,
                            Frequency = 430,
                            Word = "jackfruit"
                        },
                        new
                        {
                            WordId = 35,
                            Frequency = 440,
                            Word = "kumquat"
                        },
                        new
                        {
                            WordId = 36,
                            Frequency = 450,
                            Word = "lime"
                        },
                        new
                        {
                            WordId = 37,
                            Frequency = 460,
                            Word = "mulberry"
                        },
                        new
                        {
                            WordId = 38,
                            Frequency = 470,
                            Word = "nectar"
                        },
                        new
                        {
                            WordId = 39,
                            Frequency = 480,
                            Word = "olive"
                        },
                        new
                        {
                            WordId = 40,
                            Frequency = 490,
                            Word = "peach"
                        },
                        new
                        {
                            WordId = 41,
                            Frequency = 500,
                            Word = "plum"
                        },
                        new
                        {
                            WordId = 42,
                            Frequency = 510,
                            Word = "pomegranate"
                        },
                        new
                        {
                            WordId = 43,
                            Frequency = 520,
                            Word = "quandong"
                        },
                        new
                        {
                            WordId = 44,
                            Frequency = 530,
                            Word = "rambutan"
                        },
                        new
                        {
                            WordId = 45,
                            Frequency = 540,
                            Word = "soursop"
                        },
                        new
                        {
                            WordId = 46,
                            Frequency = 550,
                            Word = "tamarind"
                        },
                        new
                        {
                            WordId = 47,
                            Frequency = 560,
                            Word = "uglifruit"
                        },
                        new
                        {
                            WordId = 48,
                            Frequency = 570,
                            Word = "voavanga"
                        },
                        new
                        {
                            WordId = 49,
                            Frequency = 580,
                            Word = "wolfberry"
                        },
                        new
                        {
                            WordId = 50,
                            Frequency = 590,
                            Word = "ximenia"
                        },
                        new
                        {
                            WordId = 51,
                            Frequency = 600,
                            Word = "yumberry"
                        },
                        new
                        {
                            WordId = 52,
                            Frequency = 610,
                            Word = "ziziphus"
                        },
                        new
                        {
                            WordId = 53,
                            Frequency = 620,
                            Word = "almond"
                        },
                        new
                        {
                            WordId = 54,
                            Frequency = 630,
                            Word = "brazilnut"
                        },
                        new
                        {
                            WordId = 55,
                            Frequency = 640,
                            Word = "cashew"
                        },
                        new
                        {
                            WordId = 56,
                            Frequency = 650,
                            Word = "datefruit"
                        },
                        new
                        {
                            WordId = 57,
                            Frequency = 660,
                            Word = "elderberryfruit"
                        },
                        new
                        {
                            WordId = 58,
                            Frequency = 670,
                            Word = "figfruit"
                        },
                        new
                        {
                            WordId = 59,
                            Frequency = 680,
                            Word = "grapefruitfruit"
                        },
                        new
                        {
                            WordId = 60,
                            Frequency = 690,
                            Word = "hazelnut"
                        },
                        new
                        {
                            WordId = 61,
                            Frequency = 700,
                            Word = "indianalmond"
                        },
                        new
                        {
                            WordId = 62,
                            Frequency = 710,
                            Word = "jujube"
                        },
                        new
                        {
                            WordId = 63,
                            Frequency = 720,
                            Word = "kiwifruit"
                        },
                        new
                        {
                            WordId = 64,
                            Frequency = 730,
                            Word = "lemonfruit"
                        },
                        new
                        {
                            WordId = 65,
                            Frequency = 740,
                            Word = "macadamia"
                        },
                        new
                        {
                            WordId = 66,
                            Frequency = 750,
                            Word = "nectarfruit"
                        },
                        new
                        {
                            WordId = 67,
                            Frequency = 760,
                            Word = "orangefruit"
                        },
                        new
                        {
                            WordId = 68,
                            Frequency = 770,
                            Word = "peachfruit"
                        },
                        new
                        {
                            WordId = 69,
                            Frequency = 780,
                            Word = "quincefruit"
                        },
                        new
                        {
                            WordId = 70,
                            Frequency = 790,
                            Word = "raspberryfruit"
                        },
                        new
                        {
                            WordId = 71,
                            Frequency = 800,
                            Word = "strawberryfruit"
                        },
                        new
                        {
                            WordId = 72,
                            Frequency = 810,
                            Word = "tangerinefruit"
                        },
                        new
                        {
                            WordId = 73,
                            Frequency = 820,
                            Word = "uglifruitfruit"
                        },
                        new
                        {
                            WordId = 74,
                            Frequency = 830,
                            Word = "vanillafruit"
                        },
                        new
                        {
                            WordId = 75,
                            Frequency = 840,
                            Word = "watermelonfruit"
                        },
                        new
                        {
                            WordId = 76,
                            Frequency = 850,
                            Word = "xiguafruit"
                        },
                        new
                        {
                            WordId = 77,
                            Frequency = 860,
                            Word = "yellowfruitfruit"
                        },
                        new
                        {
                            WordId = 78,
                            Frequency = 870,
                            Word = "zucchinifruit"
                        },
                        new
                        {
                            WordId = 79,
                            Frequency = 880,
                            Word = "apricotfruit"
                        },
                        new
                        {
                            WordId = 80,
                            Frequency = 890,
                            Word = "blackberryfruit"
                        },
                        new
                        {
                            WordId = 81,
                            Frequency = 900,
                            Word = "cantaloupefruit"
                        },
                        new
                        {
                            WordId = 82,
                            Frequency = 910,
                            Word = "dragonfruitfruit"
                        },
                        new
                        {
                            WordId = 83,
                            Frequency = 920,
                            Word = "elderflowerfruit"
                        },
                        new
                        {
                            WordId = 84,
                            Frequency = 930,
                            Word = "figsfruit"
                        },
                        new
                        {
                            WordId = 85,
                            Frequency = 940,
                            Word = "grapefruitfruitfruit"
                        },
                        new
                        {
                            WordId = 86,
                            Frequency = 950,
                            Word = "huckleberryfruit"
                        },
                        new
                        {
                            WordId = 87,
                            Frequency = 960,
                            Word = "indianfigfruit"
                        },
                        new
                        {
                            WordId = 88,
                            Frequency = 970,
                            Word = "jackfruitfruit"
                        },
                        new
                        {
                            WordId = 89,
                            Frequency = 980,
                            Word = "kumquatfruit"
                        },
                        new
                        {
                            WordId = 90,
                            Frequency = 990,
                            Word = "limefruit"
                        },
                        new
                        {
                            WordId = 91,
                            Frequency = 1000,
                            Word = "mulberryfruit"
                        },
                        new
                        {
                            WordId = 92,
                            Frequency = 1010,
                            Word = "nectarfruitfruit"
                        },
                        new
                        {
                            WordId = 93,
                            Frequency = 1020,
                            Word = "olivefruit"
                        },
                        new
                        {
                            WordId = 94,
                            Frequency = 1030,
                            Word = "peachfruitfruit"
                        },
                        new
                        {
                            WordId = 95,
                            Frequency = 1040,
                            Word = "plumfruit"
                        },
                        new
                        {
                            WordId = 96,
                            Frequency = 1050,
                            Word = "pomegranatefruit"
                        },
                        new
                        {
                            WordId = 97,
                            Frequency = 1060,
                            Word = "quandongfruit"
                        },
                        new
                        {
                            WordId = 98,
                            Frequency = 1070,
                            Word = "rambutanfruit"
                        },
                        new
                        {
                            WordId = 99,
                            Frequency = 1080,
                            Word = "soursopfruit"
                        },
                        new
                        {
                            WordId = 100,
                            Frequency = 1090,
                            Word = "tamarindfruit"
                        });
                });

            modelBuilder.Entity("SwipeWords.Data.FlashcardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncorrectWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("SwipeWords.Data.IncorrectWord", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordId");

                    b.ToTable("IncorrectWords");

                    b.HasData(
                        new
                        {
                            WordId = 1,
                            Frequency = 50,
                            Word = "appl"
                        },
                        new
                        {
                            WordId = 2,
                            Frequency = 60,
                            Word = "banan"
                        },
                        new
                        {
                            WordId = 3,
                            Frequency = 55,
                            Word = "chery"
                        },
                        new
                        {
                            WordId = 4,
                            Frequency = 52,
                            Word = "dat"
                        },
                        new
                        {
                            WordId = 5,
                            Frequency = 51,
                            Word = "elderbery"
                        },
                        new
                        {
                            WordId = 6,
                            Frequency = 53,
                            Word = "fg"
                        },
                        new
                        {
                            WordId = 7,
                            Frequency = 54,
                            Word = "grap"
                        },
                        new
                        {
                            WordId = 8,
                            Frequency = 56,
                            Word = "honeyde"
                        },
                        new
                        {
                            WordId = 9,
                            Frequency = 57,
                            Word = "kiw"
                        },
                        new
                        {
                            WordId = 10,
                            Frequency = 58,
                            Word = "lemonn"
                        },
                        new
                        {
                            WordId = 11,
                            Frequency = 59,
                            Word = "mngo"
                        },
                        new
                        {
                            WordId = 12,
                            Frequency = 61,
                            Word = "nectarin"
                        },
                        new
                        {
                            WordId = 13,
                            Frequency = 62,
                            Word = "orane"
                        },
                        new
                        {
                            WordId = 14,
                            Frequency = 63,
                            Word = "papay"
                        },
                        new
                        {
                            WordId = 15,
                            Frequency = 64,
                            Word = "quinc"
                        },
                        new
                        {
                            WordId = 16,
                            Frequency = 65,
                            Word = "raspbery"
                        },
                        new
                        {
                            WordId = 17,
                            Frequency = 66,
                            Word = "strawbery"
                        },
                        new
                        {
                            WordId = 18,
                            Frequency = 67,
                            Word = "tangerin"
                        },
                        new
                        {
                            WordId = 19,
                            Frequency = 68,
                            Word = "uglii"
                        },
                        new
                        {
                            WordId = 20,
                            Frequency = 69,
                            Word = "vanila"
                        },
                        new
                        {
                            WordId = 21,
                            Frequency = 70,
                            Word = "watermeln"
                        },
                        new
                        {
                            WordId = 22,
                            Frequency = 71,
                            Word = "xigu"
                        },
                        new
                        {
                            WordId = 23,
                            Frequency = 72,
                            Word = "yellowfrut"
                        },
                        new
                        {
                            WordId = 24,
                            Frequency = 73,
                            Word = "zuchini"
                        },
                        new
                        {
                            WordId = 25,
                            Frequency = 74,
                            Word = "apricott"
                        },
                        new
                        {
                            WordId = 26,
                            Frequency = 75,
                            Word = "blackbery"
                        },
                        new
                        {
                            WordId = 27,
                            Frequency = 76,
                            Word = "cantalop"
                        },
                        new
                        {
                            WordId = 28,
                            Frequency = 77,
                            Word = "dragonfrut"
                        },
                        new
                        {
                            WordId = 29,
                            Frequency = 78,
                            Word = "elderflwer"
                        },
                        new
                        {
                            WordId = 30,
                            Frequency = 79,
                            Word = "figs"
                        },
                        new
                        {
                            WordId = 31,
                            Frequency = 80,
                            Word = "grapefrut"
                        },
                        new
                        {
                            WordId = 32,
                            Frequency = 81,
                            Word = "hucklberry"
                        },
                        new
                        {
                            WordId = 33,
                            Frequency = 82,
                            Word = "indianfg"
                        },
                        new
                        {
                            WordId = 34,
                            Frequency = 83,
                            Word = "jackfrut"
                        },
                        new
                        {
                            WordId = 35,
                            Frequency = 84,
                            Word = "kumquatt"
                        },
                        new
                        {
                            WordId = 36,
                            Frequency = 85,
                            Word = "limee"
                        },
                        new
                        {
                            WordId = 37,
                            Frequency = 86,
                            Word = "mulbery"
                        },
                        new
                        {
                            WordId = 38,
                            Frequency = 87,
                            Word = "nectr"
                        },
                        new
                        {
                            WordId = 39,
                            Frequency = 88,
                            Word = "oliv"
                        },
                        new
                        {
                            WordId = 40,
                            Frequency = 89,
                            Word = "pech"
                        },
                        new
                        {
                            WordId = 41,
                            Frequency = 90,
                            Word = "plumm"
                        },
                        new
                        {
                            WordId = 42,
                            Frequency = 91,
                            Word = "pomegrante"
                        },
                        new
                        {
                            WordId = 43,
                            Frequency = 92,
                            Word = "quandng"
                        },
                        new
                        {
                            WordId = 44,
                            Frequency = 93,
                            Word = "rambutn"
                        },
                        new
                        {
                            WordId = 45,
                            Frequency = 94,
                            Word = "soursop"
                        },
                        new
                        {
                            WordId = 46,
                            Frequency = 95,
                            Word = "tamrind"
                        },
                        new
                        {
                            WordId = 47,
                            Frequency = 96,
                            Word = "uglifrut"
                        },
                        new
                        {
                            WordId = 48,
                            Frequency = 97,
                            Word = "voavang"
                        },
                        new
                        {
                            WordId = 49,
                            Frequency = 98,
                            Word = "wolfbery"
                        },
                        new
                        {
                            WordId = 50,
                            Frequency = 99,
                            Word = "ximeni"
                        },
                        new
                        {
                            WordId = 51,
                            Frequency = 100,
                            Word = "yumbery"
                        },
                        new
                        {
                            WordId = 52,
                            Frequency = 101,
                            Word = "ziziphus"
                        },
                        new
                        {
                            WordId = 53,
                            Frequency = 102,
                            Word = "almond"
                        },
                        new
                        {
                            WordId = 54,
                            Frequency = 103,
                            Word = "brazilnut"
                        },
                        new
                        {
                            WordId = 55,
                            Frequency = 104,
                            Word = "cashew"
                        },
                        new
                        {
                            WordId = 56,
                            Frequency = 105,
                            Word = "datefruit"
                        },
                        new
                        {
                            WordId = 57,
                            Frequency = 106,
                            Word = "elderberryfruit"
                        },
                        new
                        {
                            WordId = 58,
                            Frequency = 107,
                            Word = "figfruit"
                        },
                        new
                        {
                            WordId = 59,
                            Frequency = 108,
                            Word = "grapefruitfruit"
                        },
                        new
                        {
                            WordId = 60,
                            Frequency = 109,
                            Word = "hazelnut"
                        },
                        new
                        {
                            WordId = 61,
                            Frequency = 110,
                            Word = "indianalmond"
                        },
                        new
                        {
                            WordId = 62,
                            Frequency = 111,
                            Word = "jujube"
                        },
                        new
                        {
                            WordId = 63,
                            Frequency = 112,
                            Word = "kiwifruit"
                        },
                        new
                        {
                            WordId = 64,
                            Frequency = 113,
                            Word = "lemonfruit"
                        },
                        new
                        {
                            WordId = 65,
                            Frequency = 114,
                            Word = "macadamia"
                        },
                        new
                        {
                            WordId = 66,
                            Frequency = 115,
                            Word = "nectarfruit"
                        },
                        new
                        {
                            WordId = 67,
                            Frequency = 116,
                            Word = "orangefruit"
                        },
                        new
                        {
                            WordId = 68,
                            Frequency = 117,
                            Word = "peachfruit"
                        },
                        new
                        {
                            WordId = 69,
                            Frequency = 118,
                            Word = "quincefruit"
                        },
                        new
                        {
                            WordId = 70,
                            Frequency = 119,
                            Word = "raspberryfruit"
                        },
                        new
                        {
                            WordId = 71,
                            Frequency = 120,
                            Word = "strawberryfruit"
                        },
                        new
                        {
                            WordId = 72,
                            Frequency = 121,
                            Word = "tangerinefruit"
                        },
                        new
                        {
                            WordId = 73,
                            Frequency = 122,
                            Word = "uglifruitfruit"
                        },
                        new
                        {
                            WordId = 74,
                            Frequency = 123,
                            Word = "vanillafruit"
                        },
                        new
                        {
                            WordId = 75,
                            Frequency = 124,
                            Word = "watermelonfruit"
                        },
                        new
                        {
                            WordId = 76,
                            Frequency = 125,
                            Word = "xiguafruit"
                        },
                        new
                        {
                            WordId = 77,
                            Frequency = 126,
                            Word = "yellowfruitfruit"
                        },
                        new
                        {
                            WordId = 78,
                            Frequency = 127,
                            Word = "zucchinifruit"
                        },
                        new
                        {
                            WordId = 79,
                            Frequency = 128,
                            Word = "apricotfruit"
                        },
                        new
                        {
                            WordId = 80,
                            Frequency = 129,
                            Word = "blackberryfruit"
                        },
                        new
                        {
                            WordId = 81,
                            Frequency = 130,
                            Word = "cantaloupefruit"
                        },
                        new
                        {
                            WordId = 82,
                            Frequency = 131,
                            Word = "dragonfruitfruit"
                        },
                        new
                        {
                            WordId = 83,
                            Frequency = 132,
                            Word = "elderflowerfruit"
                        },
                        new
                        {
                            WordId = 84,
                            Frequency = 133,
                            Word = "figsfruit"
                        },
                        new
                        {
                            WordId = 85,
                            Frequency = 134,
                            Word = "grapefruitfruitfruit"
                        },
                        new
                        {
                            WordId = 86,
                            Frequency = 135,
                            Word = "huckleberryfruit"
                        },
                        new
                        {
                            WordId = 87,
                            Frequency = 136,
                            Word = "indianfigfruit"
                        },
                        new
                        {
                            WordId = 88,
                            Frequency = 137,
                            Word = "jackfruitfruit"
                        },
                        new
                        {
                            WordId = 89,
                            Frequency = 138,
                            Word = "kumquatfruit"
                        },
                        new
                        {
                            WordId = 90,
                            Frequency = 139,
                            Word = "limefruit"
                        },
                        new
                        {
                            WordId = 91,
                            Frequency = 140,
                            Word = "mulberryfruit"
                        },
                        new
                        {
                            WordId = 92,
                            Frequency = 141,
                            Word = "nectarfruitfruit"
                        },
                        new
                        {
                            WordId = 93,
                            Frequency = 142,
                            Word = "olivefruit"
                        },
                        new
                        {
                            WordId = 94,
                            Frequency = 143,
                            Word = "peachfruitfruit"
                        },
                        new
                        {
                            WordId = 95,
                            Frequency = 144,
                            Word = "plumfruit"
                        },
                        new
                        {
                            WordId = 96,
                            Frequency = 145,
                            Word = "pomegranatefruit"
                        },
                        new
                        {
                            WordId = 97,
                            Frequency = 146,
                            Word = "quandongfruit"
                        },
                        new
                        {
                            WordId = 98,
                            Frequency = 147,
                            Word = "rambutanfruit"
                        },
                        new
                        {
                            WordId = 99,
                            Frequency = 148,
                            Word = "soursopfruit"
                        },
                        new
                        {
                            WordId = 100,
                            Frequency = 149,
                            Word = "tamarindfruit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
