version: '3.8'

services:
  swipewords:
    image: swipewords
    build:
      context: .
      dockerfile: SwipeWords/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      SA_PASSWORD: "PilkasDangus12"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"