version: '3.8'

services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "PilkasDangus12"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"